### ISSUE TITLE
Discord serverchat doesn't show player heads anymore

### ISSUE THREAD

**Issue by snaggo** [k8thekat/GatekeeperV2#69] opened 2023-01-26 11:14 UTC
At some point server-chat channels suddenly didn't display the users player head as the profile picture anymore, instead it shows the default avatar.
I can confirm that it has worked correctly before, but I don't recall any actions that could have led to this issue. I only can confirm that with my own account, as I don't have an alt-account or anything.

**Comment by k8thekat** [comment] 2023-01-28 18:14
Okay, I will be looking into this shortly. I was testing some logic and may have caused a bug to arise.

**Comment by k8thekat** [comment] 2023-02-01 00:07
I am unable to re-create this issue at this time as I do not have a large enough player base on a Test Server to cause it to fetch different player heads/etc constantly.

If you happen to notice/catch when this arises please let me know. I did some light testing and verified the player heads are working with `Default` permissions and with `Custom` permissions selected. Prefixes are working in conjunction with player heads.

I won't close this issue till we figure out the root cause. So please report back any additional finding you have.

Thanks <3

**Comment by snaggo** [comment] 2023-02-02 10:25
Well actually the issue never resolved itself.
At first it did work like intended, but on that same day approx. 30 mins later the issue started to occur. Since then, the player heads are replaced with the standard server avatar. This happens on both fabric, forge and vanilla servers with my own account.

As I also cannot re-create the issue with another account, I can provide MC/Discord Server access as well as AMP instance access if that helps. 

Thanks for your effort!

**Closed** 2023-12-17 17:30 UTC
Labels: bug
